name: Continuous Integration

on: [push, pull_request]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged
        ports:
          - 8080:8080
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/compose-action@v2


      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Start services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Tear down Docker containers
        run: |
          docker-compose down